#!/bin/sh

srcdir=$(dirname $0)
test -z "$srcdir" && srcdir=.

# Generate the documentation about compiling Window Maker
$srcdir/script/generate-txt-from-texi.sh "$srcdir/doc/build/Compilation.texi" \
					 -o "$srcdir/INSTALL-WMAKER"
$srcdir/script/generate-txt-from-texi.sh "$srcdir/doc/build/Translations.texi" \
					 -o "$srcdir/README.i18n"

# Change date of the files to the past so they will be regenerated by 'make'
touch -d '2000-01-01' $srcdir/INSTALL-WMAKER $srcdir/README.i18n

# Generate the configure script from the 'configure.ac'
autoreconf -vfi -I m4 $srcdir

exit 0

if [ -x config.status -a -z "$*" ]; then
  ./config.status --recheck
else
  if test -z "$*"; then
    echo "I am going to run ./configure with no arguments - if you wish "
    echo "to pass any to it, please specify them on the $0 command line."
    echo "If you do not wish to run ./configure, press Ctrl-C now."
    trap 'echo "configure aborted" ; exit 0' 1 2 15
    sleep 1
  fi
  ./configure "$@"
fi
