.TH "get-wings-flags" "1" "22 March 2005"
.SH "NAME"
\fBget-wings-flags\fR \- output libWINGs compile and linker flags
.PP
.SH "SYNOPSIS"
.B get-wings-flags \fR[ \fI\-\-cflags \fR] [ \fI\-\-ldflags \fR]
[ \fI\-\-libs \fR]
.PP
.SH "DESCRIPTION"
\fBget-wings-flags \fR\- output include path, library search path or
library archive names needed to compile and link with libWINGs.
.PP
.SH "OPTIONS"
.TP
.B \-\-cflags
\fRoutput include file search path to find all header files needed to compile
source code using libWINGs functions.
.TP
.B \-\-ldflags
\fRoutput library search path required to find all library archives needed to
link object files with libWINGs.
.TP
.B \-\-libs
\fRoutput library archive names required to link object filed with libWINGs.
.PP
.SH "AUTHOR"
get-wings-flags is a part of Window Maker, wich was written by
Alfredo K. Kojima <kojima@windowmaker.info> and Dan Pascu <dan@windowmaker.info>,
with contributions from many people around the Internet.
.PP
This manpage was written by Frederik Schueler <fschueler@gmx.net> for the
Debian GNU/Linux system (but may be used by others).
