.TH "wmgenmenu" "1" "15 August 2011"
.SH "NAME"
\fBwmgenmenu\fR \- Writes a menu structure usable as
~/GNUstep/Defaults/WMRootMenu to stdout
.PP
.SH "SYNOPSIS"
.B wmgenmenu \fR[ \fI\-\-options \fR]
.PP
.SH "DESCRIPTION"
\fBwmgenmenu \fR\- Writes a menu structure usable as
~/GNUstep/Defaults/WMRootMenu to stdout
.PP
.SH "OPTIONS"
.TP
.B \-\-help
\fRdisplay this help and exit
.TP
.B \-\-version
\fRoutput version information and exit
.TP
.B \-\-h
\fRlike \-\-help
.TP
.B \-\-v
\fRlike \-\-version
.PP
.SH "AUTHOR"
wmgenmenu is a part of Window Maker. It was written by Carlos R. Mafra and
Tamas TEVESZ.
.PP
This manpage was written by Rodolfo García Peñas (kix) for the
Debian GNU/Linux system (but may be used by others).
