.TH wmiv "1" "June 2015"
.SH NAME
wmiv \- quick image viewer using wrlib
.SH SYNOPSIS
.B wmiv
.RI [ \,image(s)\/ | \,directory\/ | \,archive\/]
.SH OPTIONS
.TP
.B \-\-help
display this help
.TP
.B \-\-ignore-unknown
ignore unknown image format
.TP
.B \-\-version
print version
.SH KEYS
.TP
[+]
zoom in
.TP
[\-]
zoom out
.TP
[▸]
next image
.TP
[◂]
previous image
.TP
[▴]
first image
.TP
[▾]
last image
.TP
[Ctrl+C]
copy image to clipboard
.TP
[D]
start slideshow
.TP
[Esc]
actual size
.TP
[F]
toggle full-screen mode
.TP
[L]
rotate image on the left
.TP
[Q]
quit
.TP
[R]
rotate image on the right
.SH AUTHOR
.B wmiv
is a part of Window Maker.  It was written by David Maciejak.
