.TH "wmmenugen" "1" "15 August 2011"
.SH "NAME"
\fBwmmenugen\fR \- Window Maker PropList menu generator
.PP
.SH "SYNOPSIS"
.B wmmenugen \fI\-parser:<parser> fspec \fR[ fpsec ... \fR]
\fR[\fI\-parser:<parser> fspec \fR[ fpsec ... \fR] ... \fR]
.PP
.SH "DESCRIPTION"
\fBwmmenugen \fR\- Window Maker PropList menu generator
.PP
.SH "OPTIONS"
.TP
.B \-parser
\fRspecify the parser. Known parsers are xdg and wmconfig.
.TP
.B \-fspec
\fRspecify the file.
.PP
.SH "AUTHOR"
wmmenugen is a part of Window Maker. It was written by Tamas TEVESZ.
.PP
This manpage was written by Rodolfo García Peñas (kix) for the
Debian GNU/Linux system (but may be used by others).
