debian/debianfiles/Themes/Debian.style		usr/share/WindowMaker/Themes
debian/debianfiles/Themes/DebianLegacy.style	usr/share/WindowMaker/Themes
debian/debianfiles/Themes/DebianSwirl.jpg	usr/share/WindowMaker/Backgrounds
debian/debianfiles/Themes/debian.tiff		usr/share/WindowMaker/Backgrounds
debian/debianfiles/conf/WMRootMenu		etc/GNUstep/Defaults
debian/debianfiles/conf/WMWindowAttributes	etc/GNUstep/Defaults
debian/debianfiles/conf/WindowMaker		etc/GNUstep/Defaults
debian/debianfiles/conf/plmenu.Debian		etc/GNUstep/Defaults
debian/debianfiles/wmaker			usr/bin
debian/debianfiles/wmaker-common.desktop	usr/share/xsessions
etc/GNUstep/Defaults/WMGLOBAL
etc/GNUstep/Defaults/WMState
usr/share/WINGs
usr/share/WindowMaker
usr/share/GNUstep/System/Applications/WPrefs.app/WPrefs.tiff
usr/share/GNUstep/System/Applications/WPrefs.app/WPrefs.xpm
usr/share/GNUstep/System/Applications/WPrefs.app/tiff
usr/share/locale/*/LC_MESSAGES/*.mo
