.\" Hey, Emacs!  This is an -*- nroff -*- source file.
.TH wmsetbg 1 "Leden 1999"
.SH JMÉNO
wmsetbg \- nastaví pozadí hlavního okna v X11
.SH SYNTAXE
.B wmsetbg
[\-display] [\-\-version] [\-\-help] [{\-b|\-\-back\-color} \fIbarva\fP]
[{\-t|\-\-tile}|{\-e|\-\-center}|{\-s|\-\-scale}|{\-a|\-\-maxscale} \fIobrázek\fP]
[{\-d|\-\-dither}|{\-m|\-\-match}] [\-u|\-\-update\-wmaker]
[{\-D|\-\-update\-domain} \fIdoména\fP] [{\-c|\-\-colors} \fIcpc\fP]
[{\-p|\-\-parse} \fItextura\fP] [{\-w|\-\-workspace} \fIpracovní plocha\fP]
.SH POPIS
.B wmsetbg
načítá daný
.I obrázek
(XPM, PNG, jpeg, Tiff, raw PPM) a vloží ho do hlavního okna. Obrázek je možné
zvětšit, nebo ho opakovat aby vyplnil hlavní okno. Window Maker používa
tento příkaz interně na nastavení pozadí při startu.
.SH VOLBY
.TP
.B \-a|\-\-maxscale
zvětší daný \fIobrázek\fP při dodržení poměru stran
.TP
.B \-e|\-\-center
vloží \fIobrázek\fP do středu okna
.TP
.B \-t|\-\-tile
vytvoří z \fIobrázku\fP dlaždice
.TP
.B \-s|\-\-scale
roztáhne daný \fIobrázek\fP (standartně)
.TP
.B \-d|\-\-dither
rezervuje barvy
.TP
.B \-m|\-\-match
shodné barvy
.TP
.B \-u|\-\-update\-wmaker
zapíše změnu do databáze nastavení Window Makera
.TP
.B \-D|\-\-update\-domain
zapíše změnu do databáze \fIdomény\fP
.TP
.B \-c|\-\-colors
použíje určitý počet barev na kanál
.TP
.B \-p|\-\-parse
parsuje danou \fItexturu\fP jako \fIproplist stylu textur\fP
.TP
.B \-w|\-\-workspace
nastaví pozadí jen na dané \fIpracovní ploše\fP
.TP
.B \-\-help
vypíše nápovědu
.TP
.B \-\-version
vypíše číslo verze
.SH PODÍVEJTE SE TAKÉ
.BR wmaker (1)
.SH AUTOR
Autorem Window Makera je Alfredo K. Kojima <kojima@windowmaker.info>.
wmsetbg napsal Dan Pascu <dan@windowmaker.info>
.PP
Tuto manuálovou stránku napsal Marcelo Magallon <mmagallo@debian.org>.
.PP
Do češtiny přeložil Jiří Hnídek <jiri.hnidek@vslib.cz>.
