.\" Hey, Emacs!  This is an -*- nroff -*- source file.
.TH wxcopy 1 "Září 1998"
.SH JMÉNO
wxcopy \- kopíruje standartní vstup do vyrovnávací paměti
.SH SYNOPSIS
.B wxcopy
[volby]
[soubor]
.SH POPIS
.B wxcopy
kopíruje standartní vstup nebo
.I soubor
do vyrovnávací paměti. Jakmile není dáná nějaká vyrovnávací paměť, tak se
data kopírují do vyrovnávací paměti 0 a ostaní vyrovnávací paměti rotují,
jestliže ovšem existují. Pokud je dáná vyrovnávací paměť, tak se data
kopírují do ní a nevykoná se žádné rotování.
.SH VOLBY
.TP
.B \-cutbuffer číslo
Specifikuje číslo vyrovnávací paměti, do které se budou kopírovat data.
.TP
.B \-display displej
Data se budou kopírovat do vyrovnávací paměti daného displeje/obrazovky.
.TP
.B \-nolimit
Vypne normální limit velikosti dat 64kb, čímž se umožní zvětšování vyrovnávací
paměti podla potřeby.
.TP
.B \-clearselection
Vyprázdní vlastníka PRIMARY selekce. V praxi to znamená, že když se pokusíte
vložit data prostředním tlačítkem (například), tak vloží se data z vyrovnávací
paměti 0, namísto případného spuštění selelekce myši.
.PP
.SH PODÍVEJTE SE TAKÉ
.BR wxpaste (1),
.BR wmaker (1)
.SH AUTOR
Autorem Window Makera je Alfredo K. Kojima <kojima@windowmaker.info>.
.PP
Tuto manuálovou stránku napsal Marcelo Magallon <mmagallo@debian.org>.
.PP
Do češtiny přeložil Jiří Hnídek <jiri.hnidek@vslib.cz>.
.PP
Kompatibilitu s binárními daty a \-nolimit implementoval Luke Kendall
<luke@research.canon.com.au>.
